#aws_access_key = "AKIAVFIWISPQPCZOFGSO"
#aws_secret_key = "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"
aws_region    = "us-east-1"
aws_instance_type = "t2.micro"
#aws_ami_id        = "ami-08b5b3a93ed654d19"
